import os


BASE_DIR = os.getcwd()

STYLES_DIR = os.path.join(BASE_DIR, "ui", "styles")
ICONS_DIR = os.path.join(BASE_DIR, "ui", "icons")


APP_WIDTH = 800
APP_HEIGHT = 600

SIDEBAR_WIDTH = 60
SIDEBAR_HEIGHT = 600

MANAGEBAR_WIDTH = APP_WIDTH - SIDEBAR_WIDTH
MANAGEBAR_HEIGHT = APP_HEIGHT - 555